function fig = figmode(fig, mode, varargin)
% figmode(fig, mode, figProp...)

if isnumeric(fig)
    if fig<0
        fig = clf(figure(abs(fig)));
    else
        fig = figure(fig);
    end
end
white = [0.7 0.7 0.7];

switch lower(mode)

    case 'dark'
        set(fig, ...
            'Color',[0 0 0], ...
            'NumberTitle','off', ...
            'DefaultAxesColor',[0 0 0], ...
            'DefaultAxesXColor',white, ...
            'DefaultAxesYColor',white, ...
            'DefaultAxesZColor',white, ...
            'DefaultTextColor',white, ...
            'DefaultAxesGridColor',white*0.8, ...
            'DefaultAxesMinorGridColor',white*0.6, ...
            'DefaultColorbarColor',white, ...
            'DefaultLegendTextColor',white, ...
            'DefaultAxesXGrid','on', ...
            'DefaultAxesYGrid','on', ...
            'DefaultAxesFontSize',12, ...
            'DefaultTextInterpreter','none', ...
            'DefaultAxesTickLabelInterpreter','none', ...
            'DefaultColorbarTickLabelInterpreter','none', ...
            'DefaultAxesNextPlot','add', ...
            'DefaultAxesColorOrder',[ ...
                1.0 0.4 0.4
                0.4 0.8 1.0
                1.0 1.0 0.4
                0.8 0.6 1.0
                0.4 1.0 0.6
                1.0 0.6 0.2
                0.6 0.6 0.6 ]);

    case 'default'
        set(fig, ...
            'Color','remove', ...
            'DefaultAxesColor','remove', ...
            'DefaultAxesXColor','remove', ...
            'DefaultAxesYColor','remove', ...
            'DefaultAxesZColor','remove', ...
            'DefaultTextColor','remove', ...
            'DefaultAxesGridColor','remove', ...
            'DefaultAxesMinorGridColor','remove', ...
            'DefaultColorbarColor','remove', ...
            'DefaultLegendTextColor','remove', ...
            'DefaultAxesXGrid','remove', ...
            'DefaultAxesYGrid','remove', ...
            'DefaultAxesFontSize','remove', ...
            'DefaultTextInterpreter','remove', ...
            'DefaultAxesTickLabelInterpreter','remove', ...
            'DefaultColorbarTickLabelInterpreter','remove', ...
            'DefaultAxesNextPlot','remove', ...
            'DefaultAxesColorOrder','remove');

    otherwise
        warning('figmode:UnknownMode','Unknown mode "%s"',mode)
end

% User-supplied settings
if ~isempty(varargin)
    set(fig, varargin{:})
end

if ~nargout
    clear fig
end
end
