function [SOC, discharged, charged, buy, sell] = simbattery(time, imports, exports, capacity, efficiency, maxRate, SOC0)
% Simulate the impact of a battery on electricity imports and exports.
%   SOC = simbattery(time, imports, exports, capacity, efficiency, maxRate, SOC0)
%   SOC = simbattery(__, efficiency, maxRate, SOC0)
%   [SOC, discharged, charged, buy, sell]  = simbattery(__)
%
% Inputs:
%   time       - time vector (datetime)
%   imports    - power drawn by loads (kWh)
%   exports    - power generated by PV (kWh)
%   capacity   - usable battery capacity (kWh), default 10
%   efficiency - round-trip efficiency (coef), default 0.9
%   maxRate    - max charge/discharge rate (kW), default 5
%   SOC0       - initial state of charge (kWh), default capacity*0.5
%
% Outputs:
%   SOC        - battery state of charge (kWh)
%   discharged - power drawn from battery (kWh)
%   charged    - power sent to battery, accounts for losses (kWh)
%   buy        - grid import (kWh)
%   sell       - grid export (kWh)
%
% Remarks:
% - Assumes time steps are constant.

% Defaults
if nargin<4 || isempty(capacity), capacity = 10; end
if nargin<5 || isempty(efficiency), efficiency = 0.9; end
if nargin<6 || isempty(maxRate), maxRate = 5; end
if nargin<7 || isempty(SOC0), SOC0 = capacity*0.5; end

% Initialise
timeStep = hours(mode(diff(time))); % (hours)
maxChange = maxRate * timeStep;
n = numel(time);
[SOC, discharged, charged, buy, sell] = deal(zeros(n, 1));
SOC(1) = SOC0;

% Main loop
for k = 1:n
    SOC(k) = SOC(max(k-1, 1));

    % Discharge
    possibleDischarge = min(maxChange, SOC(k));
    discharge = min(imports(k), possibleDischarge);
    SOC(k) = SOC(k) - discharge;
    discharged(k) = discharge;
    buy(k) = imports(k) - discharge;

    % Charge
    possibleCharge = min(maxChange, (capacity - SOC(k)) / efficiency);
    charge = min(exports(k), possibleCharge);
    SOC(k) = SOC(k) + charge * efficiency;
    charged(k) = charge * efficiency;
    sell(k) = exports(k) - charge;
end
end