function [soc_kwh, discharged_kwh, charged_kwh, buy_kwh, sell_kwh] = simbattery(time, import_kwh, export_kwh, capacity_kwh, efficiency, max_kw, soc0_kwh)
% Simulate the impact of a battery on electricity imports and exports.
%   soc_kwh = simbattery(time, import_kwh, export_kwh, capacity_kwh, efficiency, max_kw, soc0_kwh)
%   [soc_kwh, discharged_kwh, charged_kwh, buy_kwh, sell_kwh] = simbattery(__)
%
% Inputs:
%   time          - time vector (datetime)
%   import_kwh    - energy drawn by loads per timestep (kWh)
%   export_kwh    - energy generated by PV per timestep (kWh)
%   capacity_kwh  - usable battery capacity (kWh), default 10
%   efficiency    - round-trip efficiency (coef), default 0.9
%   max_kw        - max charge/discharge rate (kW), default 5
%   soc0_kwh      - initial state of charge (kWh), default capacity_kwh*0.5
%
% Outputs:
%   soc_kwh        - battery state of charge (kWh)
%   discharged_kwh - energy drawn from battery per timestep (kWh)
%   charged_kwh    - energy sent to battery per timestep, accounts for losses (kWh)
%   buy_kwh        - grid import per timestep (kWh)
%   sell_kwh       - grid export per timestep (kWh)
%
% Remarks:
% - Assumes time steps are constant.

% Defaults
if nargin<4 || isempty(capacity_kwh), capacity_kwh = 10; end
if nargin<5 || isempty(efficiency),   efficiency = 0.9; end
if nargin<6 || isempty(max_kw),       max_kw = 5; end
if nargin<7 || isempty(soc0_kwh),     soc0_kwh = capacity_kwh*0.5; end

% Initialise
time_step_h    = hours(mode(diff(time))); % (hours)
max_change_kwh = max_kw * time_step_h;
n = numel(time);
[soc_kwh, discharged_kwh, charged_kwh, buy_kwh, sell_kwh] = deal(zeros(n, 1));
soc_kwh(1) = soc0_kwh;

% Main loop
for k = 1:n
    soc_kwh(k) = soc_kwh(max(k-1, 1));

    % Discharge
    possible_discharge = min(max_change_kwh, soc_kwh(k));
    discharge = min(import_kwh(k), possible_discharge);
    soc_kwh(k) = soc_kwh(k) - discharge;
    discharged_kwh(k) = discharge;
    buy_kwh(k) = import_kwh(k) - discharge;

    % Charge
    possible_charge = min(max_change_kwh, (capacity_kwh - soc_kwh(k)) / efficiency);
    charge = min(export_kwh(k), possible_charge);
    soc_kwh(k) = soc_kwh(k) + charge * efficiency;
    charged_kwh(k) = charge * efficiency;
    sell_kwh(k) = export_kwh(k) - charge;
end
end
